services:
  - type: web
    name: aiogram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    build:
      environment:
        pythonVersion: 3.10.13
